@server = http://127.0.0.1:6080

@api = {{server}}/v1

###
GET {{server}}

### 
GET {{api}}

### getIntouch
POST {{api}}/users/get-in-touch
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "poppkny@email.com",
    "phoneNo": "+440711123456",
    "message": "Lorem ipseum tfh n"
}