@server = http://127.0.0.1:6080

# @server = https://sprinters-api.onrender.com


@api = {{server}}/v1

@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWYiOiI2NWM0Y2U1ZWY0YmE3YmI2OGQ5ZDlmOWMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDc2MTA3NDgsImV4cCI6MTg4MDQxMDc0OCwiYXVkIjoid2ViLXVzZXIiLCJpc3MiOiJzcHJpbnRlcnMtZGV2ZWxvcG1lbnQifQ.L8Bq_7vfCEnIV9meQ_ociSIKO-fXzI0t7zzeOtVY2Aw

###
GET {{server}}

### 
GET {{api}}

### Login
POST {{api}}/auth/login
Content-Type: application/json

{
    "email": "svfhbmwye@email.com",
    "password": "a_Great-experiencE"
}

### getIntouch
POST {{api}}/users/get-in-touch
Content-Type: application/json

{
    "firstName": "Johnni",
    "lastName": "Doree",
    "email": "poknjgop@email.com",
    "phoneNo": "+2347012898073",
    "message": "Loremy ipseum tfh n"
}

### subscribe to newsletter
POST {{api}}/users/subscribe
Content-Type: application/json


{
    "email": "amopsts@email.com"
}


#### =========== Blog ============

### create Blog
POST {{api}}/blog
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Abub",
    "description": "Buopb",
    "tags": ["egba", "rghjkue"],
    "content": "oerc",
    "blog-image": <"image-file">
}

### Get all Blogs
GET {{api}}/blog

### Get blog by Id
GET {{api}}/blog?blog_id=65b132b4b29d880c58aae887

### delete Blog
DELETE {{api}}/blog/65b132b4b29d880c58aae887
Authorization: Bearer {{token}}


### Edit blog
PATCH  {{api}}/blog/update/65afb187ef36a9f83fdd05b5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Abubub",
    "description": "Buthopb",
    "tags": ["egboa", "rghsjkue"],
    "content": "opwerc",
    "image": {
        "imageId": "sprinters/b4129df28e55301c",
        "imageUrl": "https://res.cloudinary.com/dprg3f2vd/image/upload/v1706013508/sprinters/b4129df28e55301c.jpg"
    }
}


###### ====== case study ==========

### create case study
POST {{api}}/case-study
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "projectTitle": "eddfg",
  "projectSubtitle": "vvvvvfv",
  "projectDescription": "oor3woo",
  "projectOverview": "ppdgeesppp",
  "problem": "llllsll",
  "solution": "zsss",
  "clientName": "zwed",
  "projectTimeline": "oooo",
  "projectCategory": "ppppp",
  "servicesProvides": "nnnn",
  "cover-photo": <"image-file">
}

### Edit case study
PATCH {{api}}/case-study/update/65b13373b29d880c58aae899
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "projectTitle": "asdf",
  "projectSubtitle": "vvvvv",
  "projectDescription": "oooo",
  "projectOverview": "ppppp",
  "problem": "lllll",
  "solution": "z.string()",
  "clientName": "z.string()",
  "projectTimeline": "z.string()",
  "projectCategory": "z.string()",
  "servicesProvides": "z.string()",
  "cover-photo": <"image-file">.
"imageId": "sprinters/ec90aab48e9c60f9",
}


### get all case studies
GET {{api}}/case-study

### get case study
GET {{api}}/case-study?caseStudyId=65b13373b29d880c58aae899

### delete case study
DELETE {{api}}/case-study/65b13373b29d880c58aae899
Authorization: Bearer {{token}}


###Todo remove delete blog from cloudinary after blog has been deleted